export const NORSK_MANEDER = [
  "Januar",
  "Februar",
  "Mars",
  "April",
  "Mai",
  "Juni",
  "Juli",
  "August",
  "September",
  "Oktober",
  "November",
  "Desember",
];

export const INNTEKTSBESKRIVELSER = [
  { key: "fastloenn", text: "Fastlønn" },
  { key: "timeloenn", text: "Timelønn" },
  { key: "feriepenger", text: "Feriepenger" },
  { key: "aksjerGrunnfondsbevisTilUnderkurs", text: "Aksjer grunnfondsbevis til underkurs" },
  { key: "annet", text: "Annet" },
  { key: "arbeidsoppholdKost", text: "Arbeidsopphold kost" },
  { key: "arbeidsoppholdLosji", text: "Arbeidsopphold losji" },
  { key: "beregnetSkatt", text: "Beregnet skatt" },
  { key: "besoeksreiserHjemmetAnnet", text: "Besøksreiser hjemmet annet" },
  {
    key: "besoeksreiserHjemmetKilometergodtgjoerelseBil",
    text: "Besøksreiser hjemmet kilometergodtgjørelse bil",
  },
  { key: "betaltUtenlandskSkatt", text: "Betalt utenlandsk skatt" },
  { key: "bil", text: "Bil" },
  { key: "bolig", text: "Bolig" },
  { key: "bonus", text: "Bonus" },
  { key: "bonusFraForsvaret", text: "Bonus fra forsvaret" },
  { key: "elektroniskKommunikasjon", text: "Elektronisk kommunikasjon" },
  { key: "fastBilgodtgjoerelse", text: "Fast bilgodtgjørelse" },
  { key: "fastTillegg", text: "Fast tillegg" },
  { key: "fondForIdrettsutoevere", text: "Fond for idrettsutøvere" },
  { key: "helligdagstillegg", text: "Helligdagstillegg" },
  { key: "honorarAkkordProsentProvisjon", text: "Honorar akkord prosent provisjon" },
  { key: "hyretillegg", text: "Hyretillegg" },
  {
    key: "innbetalingTilUtenlandskPensjonsordning",
    text: "Innbetaling til utenlandsk pensjonsordning",
  },
  { key: "kilometergodtgjoerelseBil", text: "Kilometergodtgjørelse bil" },
  {
    key: "kommunalOmsorgsloennOgFosterhjemsgodtgjoerelse",
    text: "Kommunal omsorgslønn og fosterhjemsgodtgjørelse",
  },
  { key: "kostDager", text: "Kost dager" },
  { key: "kostDoegn", text: "Kost døgn" },
  { key: "kostbesparelseIHjemmet", text: "Kostbesparelse i hjemmet" },
  { key: "losji", text: "Losji" },
  {
    key: "ikkeSkattepliktigLoennFraUtenlandskDiplomKonsulStasjon",
    text: "Ikke skattepliktig lønn fra utenlandsk diplom konsul stasjon",
  },
  { key: "loennForBarnepassIBarnetsHjem", text: "Lønn for barnepass i barnets hjem" },
  {
    key: "loennTilPrivatpersonerForArbeidIHjemmet",
    text: "Lønn til privatpersoner for arbeid i hjemmet",
  },
  {
    key: "loennUtbetaltAvVeldedigEllerAllmennyttigInstitusjonEllerOrganisasjon",
    text: "Lønn utbetalt av veldedig eller allmennyttig institusjon eller organisasjon",
  },
  { key: "loennTilVergeFraFylkesmannen", text: "Lønn til verge fra fylkesmannen" },
  { key: "loennTilVergeFraStatsforvalteren", text: "Lønn til verge fra statsforvalteren" },
  { key: "opsjoner", text: "Opsjoner" },
  { key: "overtidsgodtgjoerelse", text: "Overtidsgodtgjørelse" },
  { key: "reiseAnnet", text: "Reise annet" },
  { key: "reiseKost", text: "Reise kost" },
  { key: "reiseLosji", text: "Reise losji" },
  { key: "rentefordelLaan", text: "Rentefordel lån" },
  { key: "skattepliktigDelForsikringer", text: "Skattepliktig del forsikringer" },
  { key: "sluttvederlag", text: "Sluttvederlag" },
  { key: "smusstillegg", text: "Smusstillegg" },
  { key: "stipend", text: "Stipend" },
  { key: "styrehonorarOgGodtgjoerelseVerv", text: "Styrehonorar og godtgjørelse verv" },
  { key: "tips", text: "Tips" },
  { key: "skattepliktigPersonalrabatt", text: "Skattepliktig personalrabatt" },
  {
    key: "skattepliktigGodtgjoerelseSaeravtaleUtland",
    text: "Skattepliktig godtgjørelse særavtale utland",
  },
  { key: "trekkILoennForFerie", text: "Trekk i lønn for ferie" },
  {
    key: "uregelmessigeTilleggKnyttetTilArbeidetTid",
    text: "Uregelmessige tillegg knyttet til arbeidet tid",
  },
  {
    key: "uregelmessigeTilleggKnyttetTilIkkeArbeidetTid",
    text: "Uregelmessige tillegg knyttet til ikke arbeidet tid",
  },
  { key: "yrkebilTjenestligbehovKilometer", text: "Yrkebil tjenestligbehov kilometer" },
  { key: "yrkebilTjenestligbehovListepris", text: "Yrkebil tjenestligbehov listepris" },
  { key: "lottKunTrygdeavgift", text: "Lott kun trygdeavgift" },
  { key: "vederlag", text: "Vederlag" },
  { key: "dagpengerVedArbeidsloeshet", text: "Dagpenger ved arbeidsløshet" },
  {
    key: "ferietilleggDagpengerVedArbeidsloeshet",
    text: "Dagpenger ved arbeidsløshet - Ferietillegg",
  },
  { key: "dagpengerTilFisker", text: "Dagpenger til fisker" },
  { key: "dagpengerTilFiskerSomBareHarHyre", text: "Dagpenger til fisker som bare har hyre" },
  {
    key: "ferietilleggDagpengerTilFiskerSomBareHarHyre",
    text: "Dagpenger til fisker som bare har hyre - Ferietillegg",
  },
  { key: "foreldrepenger", text: "Foreldrepenger" },
  { key: "feriepengerForeldrepenger", text: "Foreldrepenger - Feriepenger" },
  { key: "svangerskapspenger", text: "Svangerskapspenger" },
  { key: "feriepengerSvangerskapspenger", text: "Svangerskapspenger - Feriepenger" },
  { key: "sykepenger", text: "Sykepenger" },
  { key: "feriepengerSykepenger", text: "Sykepenger - Feriepenger" },
  { key: "sykepengerTilFisker", text: "Sykepenger til fisker" },
  { key: "sykepengerTilFiskerSomBareHarHyre", text: "Sykepenger til fisker som bare har hyre" },
  {
    key: "feriepengerSykepengerTilFiskerSomBareHarHyre",
    text: "Sykepenger til fisker som bare har hyre - Feriepenger",
  },
  { key: "pleiepenger", text: "Pleiepenger" },
  { key: "feriepengerPleiepenger", text: "Pleiepenger - Feriepenger" },
  { key: "omsorgspenger", text: "Omsorgspenger" },
  { key: "feriepengerOmsorgspenger", text: "Omsorgspenger - Feriepenger" },
  { key: "opplaeringspenger", text: "Opplæringspenger" },
  { key: "feriepengerOpplaeringspenger", text: "Opplæringspenger - Feriepenger" },
];
